"""Make email non-nullable

Revision ID: 2675f0012f03
Revises: 5dab75a62d34
Create Date: 2025-03-27 12:33:02.566278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2675f0012f03'
down_revision: Union[str, None] = '5dab75a62d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email', nullable=True)
    # ### end Alembic commands ###
